version: "3.9"

services:
  app:
    image: cts
    ports:
      - "5050:5000"
    restart: unless-stopped
    depends_on: 
      - db
  db:
    image: mysql
    ports:
      - "3200:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
